// src-react/components/database/TableDesignerForeignKeys.tsx
import { useTranslation } from 'react-i18next'
import { Button, Space, Table } from 'antd'
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import type { ColumnsType } from 'antd/es/table'
import type { DesignerForeignKey } from './designerTypes'
import styles from './TableDesignerSection.module.css'

/** 外键列表（对等 Vue 版 TableDesignerForeignKeys.vue） */

interface TableDesignerForeignKeysProps {
  foreignKeys: DesignerForeignKey[]
  loading: boolean
  readOnly?: boolean
  onAdd: () => void
  onRemove: (record: DesignerForeignKey) => void
}

export default function TableDesignerForeignKeys({ foreignKeys, loading, readOnly, onAdd, onRemove }: TableDesignerForeignKeysProps) {
  const { t } = useTranslation()

  const displayColumns: ColumnsType<DesignerForeignKey> = [
    { title: t('designer.fk_name'), dataIndex: 'name', key: 'name' },
    { title: t('designer.fk_column'), dataIndex: 'column_name', key: 'column_name' },
    { title: t('designer.ref_table'), dataIndex: 'referenced_table_name', key: 'referenced_table_name' },
    { title: t('designer.ref_column'), dataIndex: 'referenced_column_name', key: 'referenced_column_name' },
    ...(!readOnly ? [{
      title: t('common.delete'), dataIndex: 'operation', width: 100,
      render: (_: unknown, record: DesignerForeignKey) => (
        <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={() => onRemove(record)}>
          {t('common.delete')}
        </Button>
      ),
    }] : []),
  ]

  return (
    <div className={styles.designerSection}>
      {!readOnly && (
        <Space className={styles.designerActions}>
          <Button icon={<PlusOutlined />} onClick={onAdd} type="primary">
            {t('designer.add_fk')}
          </Button>
        </Space>
      )}
      <Table
        columns={displayColumns}
        dataSource={foreignKeys}
        loading={loading}
        pagination={false}
        size="small"
        bordered
        rowKey="name"
      />
    </div>
  )
}

// src/components/database/TableDesignerForeignKeys.vue
<template>
  <div class="designer-section">
    <a-space v-if="!readOnly" class="designer-actions">
      <a-button :icon="h(PlusOutlined)" @click="$emit('add')" type="primary">
        {{ $t('designer.add_fk') }}
      </a-button>
    </a-space>

    <a-table
      :columns="readOnly ? displayColumns.filter(c => c.dataIndex !== 'operation') : displayColumns"
      :data-source="foreignKeys"
      :loading="loading"
      :pagination="false"
      size="small"
      bordered
      row-key="name"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.dataIndex === 'operation'">
          <a-button
            type="text"
            size="small"
            danger
            :icon="h(DeleteOutlined)"
            @click="$emit('remove', record)"
          >
            {{ $t('common.delete') }}
          </a-button>
        </template>
      </template>
    </a-table>
  </div>
</template>

<script setup lang="ts">
import { h, computed } from 'vue'
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons-vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

defineProps<{
  foreignKeys: any[]
  loading: boolean
  readOnly?: boolean
}>()

defineEmits<{
  add: []
  remove: [record: any]
}>()

const displayColumns = computed(() => [
  { title: t('designer.fk_name'), dataIndex: 'name', key: 'name' },
  { title: t('designer.fk_column'), dataIndex: 'column_name', key: 'column_name' },
  { title: t('designer.ref_table'), dataIndex: 'referenced_table_name', key: 'referenced_table_name' },
  { title: t('designer.ref_column'), dataIndex: 'referenced_column_name', key: 'referenced_column_name' },
  { title: t('common.delete'), dataIndex: 'operation', width: 100 },
])
</script>

<style scoped>
.designer-section {
  padding: 16px;
}

.designer-actions {
  margin-bottom: 16px;
}
</style>
