// src-react/components/database/TableDesignerIndexes.tsx
import { useTranslation } from 'react-i18next'
import { Button, Space, Table } from 'antd'
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import type { ColumnsType } from 'antd/es/table'
import type { DesignerIndex } from './designerTypes'
import styles from './TableDesignerSection.module.css'

/** 索引列表（对等 Vue 版 TableDesignerIndexes.vue） */

interface TableDesignerIndexesProps {
  indexes: DesignerIndex[]
  loading: boolean
  readOnly?: boolean
  onAdd: () => void
  onRemove: (record: DesignerIndex) => void
}

export default function TableDesignerIndexes({ indexes, loading, readOnly, onAdd, onRemove }: TableDesignerIndexesProps) {
  const { t } = useTranslation()

  const displayColumns: ColumnsType<DesignerIndex> = [
    { title: t('designer.index_name'), dataIndex: 'name', key: 'name' },
    {
      title: t('designer.index_columns'), dataIndex: 'columns', key: 'columns',
      render: (text) => Array.isArray(text) ? text.join(', ') : text,
    },
    { title: t('designer.index_type'), dataIndex: 'index_type', key: 'index_type' },
    {
      title: t('designer.unique'), dataIndex: 'is_unique', key: 'is_unique',
      render: (text) => text ? t('common.ok') : '-',
    },
    ...(!readOnly ? [{
      title: t('common.delete'), dataIndex: 'operation', width: 100,
      render: (_: unknown, record: DesignerIndex) => (
        <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={() => onRemove(record)}>
          {t('common.delete')}
        </Button>
      ),
    }] : []),
  ]

  return (
    <div className={styles.designerSection}>
      {!readOnly && (
        <Space className={styles.designerActions}>
          <Button icon={<PlusOutlined />} onClick={onAdd} type="primary">
            {t('designer.add_index')}
          </Button>
        </Space>
      )}
      <Table
        columns={displayColumns}
        dataSource={indexes}
        loading={loading}
        pagination={false}
        size="small"
        bordered
        rowKey="name"
      />
    </div>
  )
}

// src/components/database/TableDesignerIndexes.vue
<template>
  <div class="designer-section">
    <a-space v-if="!readOnly" class="designer-actions">
      <a-button :icon="h(PlusOutlined)" @click="$emit('add')" type="primary">
        {{ $t('designer.add_index') }}
      </a-button>
    </a-space>

    <a-table
      :columns="readOnly ? displayColumns.filter(c => c.dataIndex !== 'operation') : displayColumns"
      :data-source="indexes"
      :loading="loading"
      :pagination="false"
      size="small"
      bordered
      row-key="name"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.dataIndex === 'operation'">
          <a-button
            type="text"
            size="small"
            danger
            :icon="h(DeleteOutlined)"
            @click="$emit('remove', record)"
          >
            {{ $t('common.delete') }}
          </a-button>
        </template>
      </template>
    </a-table>
  </div>
</template>

<script setup lang="ts">
import { h, computed } from 'vue'
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons-vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

defineProps<{
  indexes: any[]
  loading: boolean
  readOnly?: boolean
}>()

defineEmits<{
  add: []
  remove: [record: any]
}>()

const displayColumns = computed(() => [
  { title: t('designer.index_name'), dataIndex: 'name', key: 'name' },
  { title: t('designer.index_columns'), dataIndex: 'columns', key: 'columns', customRender: ({ text }: any) => Array.isArray(text) ? text.join(', ') : text },
  { title: t('designer.index_type'), dataIndex: 'index_type', key: 'index_type' },
  { title: t('designer.unique'), dataIndex: 'is_unique', key: 'is_unique',
    customRender: ({ text }: any) => text ? t('common.ok') : '-' },
  { title: t('common.delete'), dataIndex: 'operation', width: 100 },
])
</script>

<style scoped>
.designer-section {
  padding: 16px;
}

.designer-actions {
  margin-bottom: 16px;
}
</style>
