// src/components/search/GlobalSearch.tsx
import { useEffect, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { Button, Checkbox, Empty, Input, List, Modal, Select, Space, Tabs, Tag } from 'antd'
import {
  CopyOutlined, EyeOutlined, FileOutlined, FolderOutlined, SearchOutlined, TableOutlined,
} from '@ant-design/icons'
import { message } from '../../ui/antd'
import { metadataApi } from '@/api'
import type { DatabaseInfo } from '@/types/database'
import { writeClipboardText } from '@/utils/clipboard'
import { useConnectionStore } from '../../stores/connectionStore'
import styles from './GlobalSearch.module.css'

/**
 * 全局搜索（对等 Vue 版 GlobalSearch.vue）。
 * 前端全量拉取 + 客户端过滤的 N+1 现状保留（已知业务问题 5，仅回车触发是刻意行为）；
 * scope 规则照抄（非 PG 才显示存储过程）；v-html 高亮改**分段渲染**（计划 Slice 21 要点）。
 * 走 Slice 2 已收编的 metadataApi.getFunctions/getProcedures（含断线自动重连）。
 */

interface SearchResult {
  type: 'table' | 'column' | 'view' | 'procedure' | 'function' | 'trigger'
  name: string
  database?: string
  table?: string
  dataType?: string
  comment?: string
}

interface GlobalSearchProps {
  open: boolean
  connectionId: string | null
  onClose: () => void
  onViewData: (data: { database?: string; table: string }) => void
}

/** 高亮分段渲染（替代 Vue 的 v-html）：split 捕获组后奇数下标即命中片段 */
function HighlightedText({ text, keyword, caseSensitive }: { text: string; keyword: string; caseSensitive: boolean }) {
  if (!keyword) return <>{text}</>
  const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const regex = new RegExp(`(${escaped})`, caseSensitive ? 'g' : 'gi')
  const parts = text.split(regex)
  return (
    <>
      {parts.map((part, i) => (
        i % 2 === 1
          ? <span key={i} className={styles.highlight}>{part}</span>
          : <span key={i}>{part}</span>
      ))}
    </>
  )
}

export default function GlobalSearch({ open, connectionId, onClose, onViewData }: GlobalSearchProps) {
  const { t } = useTranslation()

  const currentConnection = useConnectionStore((s) => (connectionId ? s.connections.find((conn) => conn.id === connectionId) || null : null))
  const isPostgreSQL = (currentConnection?.db_type || '').toLowerCase() === 'postgresql'

  const [searchText, setSearchText] = useState('')
  const [searching, setSearching] = useState(false)
  const [searchScope, setSearchScope] = useState('all')
  const [selectedDatabase, setSelectedDatabase] = useState('')
  const [caseSensitive, setCaseSensitive] = useState(false)
  const [searchResults, setSearchResults] = useState<SearchResult[]>([])
  const [databases, setDatabases] = useState<DatabaseInfo[]>([])
  const [activeTab, setActiveTab] = useState('all')

  // 打开时加载数据库列表并重置（对等 watch(visible)）
  useEffect(() => {
    if (!open) return
    setSearchResults([])
    setActiveTab('all')
    if (connectionId) {
      void (async () => {
        try {
          setDatabases(await metadataApi.getDatabases(connectionId))
        } catch (error: unknown) {
          console.error('Failed to load databases:', error)
        }
      })()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  const resultTypes = [
    { key: 'all', label: t('search.scope_all') },
    { key: 'table', label: t('search.scope_tables') },
    { key: 'column', label: t('search.scope_columns') },
    { key: 'view', label: t('search.scope_views') },
    ...(isPostgreSQL ? [] : [{ key: 'procedure', label: t('search.scope_procedures') }]),
    { key: 'function', label: t('search.scope_functions') },
  ]

  function getIcon(type: string): ReactNode {
    if (type === 'table') return <TableOutlined className={styles.resultIcon} />
    if (type === 'view') return <EyeOutlined className={styles.resultIcon} />
    if (type === 'procedure' || type === 'function' || type === 'trigger') return <FolderOutlined className={styles.resultIcon} />
    return <FileOutlined className={styles.resultIcon} />
  }

  function getTypeName(type: string): string {
    const keyMap: Record<string, string> = {
      table: 'search.type_table',
      column: 'search.type_column',
      view: 'search.type_view',
      procedure: 'search.type_procedure',
      function: 'search.type_function',
      trigger: 'search.type_trigger',
    }
    return keyMap[type] ? t(keyMap[type]) : type
  }

  function getResultCount(type: string): number {
    if (type === 'all') return searchResults.length
    return searchResults.filter((r) => r.type === type).length
  }

  function getResultsByType(type: string): SearchResult[] {
    if (type === 'all') return searchResults
    return searchResults.filter((r) => r.type === type)
  }

  async function handleSearch() {
    if (!searchText || !connectionId) {
      message.warning(t('search.input_required'))
      return
    }

    setSearching(true)
    setSearchResults([])

    try {
      const results: SearchResult[] = []
      const searchPattern = caseSensitive ? searchText : searchText.toLowerCase()

      const databasesToSearch = selectedDatabase
        ? [{ name: selectedDatabase }]
        : databases

      for (const db of databasesToSearch) {
        if (searchScope === 'all' || searchScope === 'tables') {
          const tables = await metadataApi.getTables(connectionId, db.name)
          for (const table of tables) {
            const tableName = caseSensitive ? table.name : table.name.toLowerCase()
            if (tableName.includes(searchPattern)) {
              results.push({ type: 'table', name: table.name, database: db.name, comment: table.comment })
            }
          }
        }

        if (searchScope === 'all' || searchScope === 'columns') {
          const tables = await metadataApi.getTables(connectionId, db.name)
          for (const table of tables) {
            const columns = await metadataApi.getTableStructure({
              connectionId,
              table: table.name,
              schema: table.schema || db.name,
              database: db.name,
            })
            for (const column of columns) {
              const columnName = caseSensitive ? column.name : column.name.toLowerCase()
              if (columnName.includes(searchPattern)) {
                results.push({
                  type: 'column',
                  name: column.name,
                  database: db.name,
                  table: table.name,
                  dataType: column.data_type,
                  comment: column.comment,
                })
              }
            }
          }
        }

        if (searchScope === 'all' || searchScope === 'views') {
          try {
            const views = await metadataApi.getViews(connectionId, db.name)
            for (const view of views) {
              const viewName = caseSensitive ? view.name : view.name.toLowerCase()
              if (viewName.includes(searchPattern)) {
                results.push({ type: 'view', name: view.name, database: db.name, comment: view.comment })
              }
            }
          } catch (error) {
            console.error('Failed to search views:', error)
          }
        }

        if (!isPostgreSQL && (searchScope === 'all' || searchScope === 'procedures')) {
          try {
            const procedures = await metadataApi.getProcedures(connectionId, db.name)
            for (const proc of procedures) {
              const procName = caseSensitive ? proc.ROUTINE_NAME : proc.ROUTINE_NAME.toLowerCase()
              if (procName.includes(searchPattern)) {
                results.push({ type: 'procedure', name: proc.ROUTINE_NAME, database: db.name })
              }
            }
          } catch (error) {
            console.error('Failed to search procedures:', error)
          }
        }

        if (searchScope === 'all' || searchScope === 'functions') {
          try {
            const functions = await metadataApi.getFunctions(connectionId, db.name)
            for (const func of functions) {
              const funcName = caseSensitive ? func.ROUTINE_NAME : func.ROUTINE_NAME.toLowerCase()
              if (funcName.includes(searchPattern)) {
                results.push({ type: 'function', name: func.ROUTINE_NAME, database: db.name })
              }
            }
          } catch (error) {
            console.error('Failed to search functions:', error)
          }
        }
      }

      setSearchResults(results)

      if (results.length === 0) {
        message.info(t('search.no_results_message'))
      } else {
        message.success(t('search.results_success', { n: results.length }))
      }
    } catch (error: unknown) {
      message.error(t('search.fail', { error: String(error) }))
    } finally {
      setSearching(false)
    }
  }

  function handleResultClick(item: SearchResult) {
    if (item.type === 'table' || item.type === 'view') {
      onViewData({ database: item.database, table: item.name })
    }
  }

  function handleViewData(item: SearchResult) {
    onViewData({ database: item.database, table: item.name })
    onClose()
  }

  async function handleCopyPath(item: SearchResult) {
    const path = item.table
      ? `${item.database}.${item.table}.${item.name}`
      : `${item.database}.${item.name}`
    await writeClipboardText(path)
    message.success(t('search.path_copied'))
  }

  const renderResultList = (typeKey: string) => (
    <List
      dataSource={getResultsByType(typeKey)}
      pagination={{ pageSize: 20 }}
      renderItem={(item) => (
        <List.Item
          actions={[
            <Button key="copy" type="link" size="small" onClick={() => void handleCopyPath(item)}>
              <CopyOutlined /> {t('common.copy_path')}
            </Button>,
            ...(item.type === 'table' ? [(
              <Button key="view" type="link" size="small" onClick={() => handleViewData(item)}>
                <TableOutlined /> {t('tree.view_data')}
              </Button>
            )] : []),
          ]}
        >
          <List.Item.Meta
            avatar={getIcon(item.type)}
            title={(
              <>
                <a onClick={() => handleResultClick(item)}>
                  <HighlightedText text={item.name} keyword={searchText} caseSensitive={caseSensitive} />
                </a>
                {item.database && <Tag color="blue" className={styles.resultTagDatabase}>{item.database}</Tag>}
                {item.table && <Tag color="green" className={styles.resultTagTable}>{item.table}</Tag>}
              </>
            )}
            description={(
              <div>
                {item.type && <span>{getTypeName(item.type)}</span>}
                {item.dataType && <span> • {t('search.type_prefix')}: {item.dataType}</span>}
                {item.comment && <span> • {item.comment}</span>}
              </div>
            )}
          />
        </List.Item>
      )}
    />
  )

  return (
    <Modal open={open} title={t('search.title')} width={1000} onCancel={onClose} footer={null}>
      <div className={styles.globalSearch}>
        <div className={`section-header ${styles.searchHeader}`}>
          <Input.Search
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            placeholder={t('search.placeholder')}
            size="large"
            onSearch={() => void handleSearch()}
            loading={searching}
            allowClear
            autoFocus
            enterButton={(
              <Button type="primary">
                <SearchOutlined /> {t('search.button')}
              </Button>
            )}
          />

          <div className={`${styles.searchFilters} ${styles.searchFiltersSpaced}`}>
            <Space>
              <Select
                value={searchScope}
                onChange={setSearchScope}
                className={styles.searchFilterSelect}
                placeholder={t('search.scope')}
                options={[
                  { value: 'all', label: t('search.scope_all') },
                  { value: 'tables', label: t('search.scope_tables') },
                  { value: 'columns', label: t('search.scope_columns') },
                  { value: 'views', label: t('search.scope_views') },
                  ...(isPostgreSQL ? [] : [{ value: 'procedures', label: t('search.scope_procedures') }]),
                  { value: 'functions', label: t('search.scope_functions') },
                ]}
              />
              <Select
                value={selectedDatabase}
                onChange={(v) => setSelectedDatabase(String(v ?? ''))}
                className={styles.searchFilterSelect}
                placeholder={t('search.select_database')}
                allowClear
                options={[
                  { value: '', label: t('search.all_databases') },
                  ...databases.map((db) => ({ value: db.name, label: db.name })),
                ]}
              />
              <Checkbox checked={caseSensitive} onChange={(e) => setCaseSensitive(e.target.checked)}>
                {t('search.case_sensitive')}
              </Checkbox>
            </Space>
          </div>
        </div>

        {searchResults.length > 0 ? (
          <div className={styles.searchResults}>
            <div className={`text-subtle ${styles.resultsSummary}`}>
              {t('search.results_found')} <strong>{searchResults.length}</strong> {t('search.results_count')}
            </div>
            <Tabs
              activeKey={activeTab}
              onChange={setActiveTab}
              items={resultTypes.map((type) => ({
                key: type.key,
                label: `${type.label} (${getResultCount(type.key)})`,
                children: renderResultList(type.key),
              }))}
            />
          </div>
        ) : (!searching && searchText) ? (
          <Empty description={t('search.no_results')} />
        ) : null}
      </div>
    </Modal>
  )
}

// src/components/search/GlobalSearch.vue
<template>
  <a-modal
    :open="visible"
    :title="$t('search.title')"
    :width="1000"
    @cancel="handleCancel"
    :footer="null"
  >
    <div class="global-search">
      <div class="section-header search-header">
        <a-input-search
          v-model:value="searchText"
          :placeholder="$t('search.placeholder')"
          size="large"
          @search="handleSearch"
          :loading="searching"
          allow-clear
          autofocus
        >
          <template #enterButton>
            <a-button type="primary">
              <SearchOutlined />
              {{ $t('search.button') }}
            </a-button>
          </template>
        </a-input-search>

        <div class="search-filters search-filters-spaced">
          <a-space>
            <a-select
              v-model:value="searchScope"
              class="search-filter-select"
              :placeholder="$t('search.scope')"
            >
              <a-select-option value="all">{{ $t('search.scope_all') }}</a-select-option>
              <a-select-option value="tables">{{ $t('search.scope_tables') }}</a-select-option>
              <a-select-option value="columns">{{ $t('search.scope_columns') }}</a-select-option>
              <a-select-option value="views">{{ $t('search.scope_views') }}</a-select-option>
              <a-select-option v-if="!isPostgreSQL" value="procedures">{{ $t('search.scope_procedures') }}</a-select-option>
              <a-select-option value="functions">{{ $t('search.scope_functions') }}</a-select-option>
            </a-select>

            <a-select
              v-model:value="selectedDatabase"
              class="search-filter-select"
              :placeholder="$t('search.select_database')"
              allow-clear
            >
              <a-select-option value="">{{ $t('search.all_databases') }}</a-select-option>
              <a-select-option
                v-for="db in databases"
                :key="db.name"
                :value="db.name"
              >
                {{ db.name }}
              </a-select-option>
            </a-select>

            <a-checkbox v-model:checked="caseSensitive">
              {{ $t('search.case_sensitive') }}
            </a-checkbox>
          </a-space>
        </div>
      </div>

      <div class="search-results" v-if="searchResults.length > 0">
        <div class="text-subtle results-summary">
          {{ $t('search.results_found') }} <strong>{{ searchResults.length }}</strong> {{ $t('search.results_count') }}
        </div>

        <a-tabs v-model:activeKey="activeTab">
          <a-tab-pane
            v-for="type in resultTypes"
            :key="type.key"
            :tab="`${type.label} (${getResultCount(type.key)})`"
          >
            <a-list
              :data-source="getResultsByType(type.key)"
              :pagination="{ pageSize: 20 }"
            >
              <template #renderItem="{ item }">
                <a-list-item>
                  <a-list-item-meta>
                    <template #avatar>
                      <component :is="getIcon(item.type)" class="result-icon" />
                    </template>
                    <template #title>
                      <a @click="handleResultClick(item)">
                        <span v-html="highlightMatch(item.name)"></span>
                      </a>
                      <a-tag
                        v-if="item.database"
                        color="blue"
                        size="small"
                        class="result-tag result-tag-database"
                      >
                        {{ item.database }}
                      </a-tag>
                      <a-tag
                        v-if="item.table"
                        color="green"
                        size="small"
                        class="result-tag result-tag-table"
                      >
                        {{ item.table }}
                      </a-tag>
                    </template>
                    <template #description>
                      <div>
                        <span v-if="item.type">{{ getTypeName(item.type) }}</span>
                        <span v-if="item.dataType"> • {{ $t('search.type_prefix') }}: {{ item.dataType }}</span>
                        <span v-if="item.comment"> • {{ item.comment }}</span>
                      </div>
                    </template>
                  </a-list-item-meta>
                  <template #actions>
                    <a-button
                      type="link"
                      size="small"
                      @click="handleCopyPath(item)"
                    >
                      <CopyOutlined />
                      {{ $t('common.copy_path') }}
                    </a-button>
                    <a-button
                      v-if="item.type === 'table'"
                      type="link"
                      size="small"
                      @click="handleViewData(item)"
                    >
                      <TableOutlined />
                      {{ $t('tree.view_data') }}
                    </a-button>
                  </template>
                </a-list-item>
              </template>
            </a-list>
          </a-tab-pane>
        </a-tabs>
      </div>

      <a-empty
        v-else-if="!searching && searchText"
        :description="$t('search.no_results')"
      />
    </div>
  </a-modal>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useConnectionStore } from '@/stores/connection'
import {
  SearchOutlined,
  CopyOutlined,
  TableOutlined,
  EyeOutlined,
  FileOutlined,
  FolderOutlined,
} from '@ant-design/icons-vue'
import { message } from '@/ui/antd'
import { useI18n } from 'vue-i18n'
import { metadataApi } from '@/api'
import type { DatabaseInfo } from '@/types/database'
import { writeClipboardText } from '@/utils/clipboard'

interface SearchResult {
  type: 'table' | 'column' | 'view' | 'procedure' | 'function' | 'trigger'
  name: string
  database?: string
  table?: string
  dataType?: string
  comment?: string
}

const { t } = useI18n()
const connectionStore = useConnectionStore()
const currentConnection = computed(() => props.connectionId ? connectionStore.connections.find(conn => conn.id === props.connectionId) || null : null)
const isPostgreSQL = computed(() => (currentConnection.value?.db_type || '').toLowerCase() === 'postgresql')

const props = defineProps<{
  visible: boolean
  connectionId: string | null
}>()

const emit = defineEmits(['update:visible', 'view-data', 'design-table'])

const searchText = ref('')
const searching = ref(false)
const searchScope = ref('all')
const selectedDatabase = ref('')
const caseSensitive = ref(false)
const searchResults = ref<SearchResult[]>([])
const databases = ref<DatabaseInfo[]>([])
const activeTab = ref('all')

const resultTypes = computed(() => [
  { key: 'all', label: t('search.scope_all') },
  { key: 'table', label: t('search.scope_tables') },
  { key: 'column', label: t('search.scope_columns') },
  { key: 'view', label: t('search.scope_views') },
  ...(isPostgreSQL.value ? [] : [{ key: 'procedure', label: t('search.scope_procedures') }]),
  { key: 'function', label: t('search.scope_functions') },
])

// 获取图标
function getIcon(type: string) {
  const iconMap: Record<string, typeof TableOutlined> = {
    table: TableOutlined,
    column: FileOutlined,
    view: EyeOutlined,
    procedure: FolderOutlined,
    function: FolderOutlined,
    trigger: FolderOutlined,
  }
  return iconMap[type] || FileOutlined
}

// 获取类型名称
function getTypeName(type: string): string {
  const keyMap: Record<string, string> = {
    table: 'search.type_table',
    column: 'search.type_column',
    view: 'search.type_view',
    procedure: 'search.type_procedure',
    function: 'search.type_function',
    trigger: 'search.type_trigger',
  }
  return keyMap[type] ? t(keyMap[type]) : type
}

// 获取指定类型的结果数量
function getResultCount(type: string): number {
  if (type === 'all') return searchResults.value.length
  return searchResults.value.filter(r => r.type === type).length
}

// 获取指定类型的结果
function getResultsByType(type: string): SearchResult[] {
  if (type === 'all') return searchResults.value
  return searchResults.value.filter(r => r.type === type)
}

// 高亮匹配文本
function highlightMatch(text: string): string {
  if (!searchText.value) return text

  const regex = new RegExp(
    `(${searchText.value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`,
    caseSensitive.value ? 'g' : 'gi'
  )

  return text.replace(regex, '<span class="global-search-highlight">$1</span>')
}

// 加载数据库列表
async function loadDatabases() {
  if (!props.connectionId) return

  try {
    const dbs = await metadataApi.getDatabases(props.connectionId!)
    databases.value = dbs
  } catch (error: unknown) {
    console.error('Failed to load databases:', error)
  }
}

// 执行搜索
async function handleSearch() {
  if (!searchText.value || !props.connectionId) {
    message.warning(t('search.input_required'))
    return
  }

  searching.value = true
  searchResults.value = []

  try {
    const results: SearchResult[] = []
    const searchPattern = caseSensitive.value ? searchText.value : searchText.value.toLowerCase()

    // 确定要搜索的数据库列表
    const databasesToSearch = selectedDatabase.value
      ? [{ name: selectedDatabase.value }]
      : databases.value

    for (const db of databasesToSearch) {
      // 搜索表
      if (searchScope.value === 'all' || searchScope.value === 'tables') {
        const tables = await metadataApi.getTables(props.connectionId!, db.name)

        for (const table of tables) {
          const tableName = caseSensitive.value ? table.name : table.name.toLowerCase()
          if (tableName.includes(searchPattern)) {
            results.push({
              type: 'table',
              name: table.name,
              database: db.name,
              comment: table.comment,
            })
          }
        }
      }

      // 搜索列
      if (searchScope.value === 'all' || searchScope.value === 'columns') {
        const tables = await metadataApi.getTables(props.connectionId!, db.name)

        for (const table of tables) {
          const columns = await metadataApi.getTableStructure({
            connectionId: props.connectionId!,
            table: table.name,
            schema: table.schema || db.name,
            database: db.name,
          })

          for (const column of columns) {
            const columnName = caseSensitive.value ? column.name : column.name.toLowerCase()
            if (columnName.includes(searchPattern)) {
              results.push({
                type: 'column',
                name: column.name,
                database: db.name,
                table: table.name,
                dataType: column.data_type,
                comment: column.comment,
              })
            }
          }
        }
      }

      // 搜索视图
      if (searchScope.value === 'all' || searchScope.value === 'views') {
        try {
          const views = await metadataApi.getViews(props.connectionId!, db.name)

          for (const view of views) {
            const viewName = caseSensitive.value ? view.name : view.name.toLowerCase()
            if (viewName.includes(searchPattern)) {
              results.push({
                type: 'view',
                name: view.name,
                database: db.name,
                comment: view.comment,
              })
            }
          }
        } catch (error) {
          console.error('Failed to search views:', error)
        }
      }

      // 搜索存储过程（MySQL 等支持的数据库）
      if (!isPostgreSQL.value && (searchScope.value === 'all' || searchScope.value === 'procedures')) {
        try {
          const procedures = await metadataApi.getProcedures(props.connectionId!, db.name)

          for (const proc of procedures) {
            const procName = caseSensitive.value ? proc.ROUTINE_NAME : proc.ROUTINE_NAME.toLowerCase()
            if (procName.includes(searchPattern)) {
              results.push({
                type: 'procedure',
                name: proc.ROUTINE_NAME,
                database: db.name,
              })
            }
          }
        } catch (error) {
          console.error('Failed to search procedures:', error)
        }
      }

      // 搜索函数
      if (searchScope.value === 'all' || searchScope.value === 'functions') {
        try {
          const functions = await metadataApi.getFunctions(props.connectionId!, db.name)

          for (const func of functions) {
            const funcName = caseSensitive.value ? func.ROUTINE_NAME : func.ROUTINE_NAME.toLowerCase()
            if (funcName.includes(searchPattern)) {
              results.push({
                type: 'function',
                name: func.ROUTINE_NAME,
                database: db.name,
              })
            }
          }
        } catch (error) {
          console.error('Failed to search functions:', error)
        }
      }
    }

    searchResults.value = results

    if (results.length === 0) {
      message.info(t('search.no_results_message'))
    } else {
      message.success(t('search.results_success', { n: results.length }))
    }
  } catch (error: unknown) {
    message.error(t('search.fail', { error: String(error) }))
  } finally {
    searching.value = false
  }
}

// 处理结果点击
function handleResultClick(item: SearchResult) {
  if (item.type === 'table' || item.type === 'view') {
    emit('view-data', {
      database: item.database,
      table: item.name,
    })
  }
}

// 查看数据
function handleViewData(item: SearchResult) {
  emit('view-data', {
    database: item.database,
    table: item.name,
  })
  emit('update:visible', false)
}

// 复制路径
async function handleCopyPath(item: SearchResult) {
  let path = ''
  if (item.table) {
    path = `${item.database}.${item.table}.${item.name}`
  } else {
    path = `${item.database}.${item.name}`
  }

  await writeClipboardText(path)
  message.success(t('search.path_copied'))
}

// 取消
function handleCancel() {
  emit('update:visible', false)
}

// 监听对话框打开
watch(() => props.visible, (visible) => {
  if (visible) {
    loadDatabases()
    searchResults.value = []
    activeTab.value = 'all'
  }
})
</script>

<style scoped>
.global-search {
  min-height: 500px;
}

.search-header {
  margin-bottom: 24px;
}

.search-filters {
  display: flex;
  align-items: center;
  gap: 12px;
}

.search-filters-spaced {
  margin-top: 12px;
}

.search-filter-select {
  width: 150px;
}

.results-summary {
  padding: 12px 0;
  font-size: 14px;
}

.search-results {
  margin-top: 16px;
}

.result-icon {
  font-size: 20px;
  color: var(--color-primary);
}

.result-tag-database {
  margin-left: 8px;
}

.result-tag-table {
  margin-left: 4px;
}

:deep(.global-search-highlight) {
  background-color: var(--color-warning-soft-bg);
  color: var(--app-text);
  font-weight: 700;
}

:deep(.ant-list-item-meta-title) a {
  color: inherit;
}

:deep(.ant-list-item-meta-title) a:hover {
  color: var(--color-primary);
}
</style>
