// src/components/settings/SettingsContent.tsx
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Alert, Input, InputNumber, Select } from 'antd'
import { useAppStore, useAppTheme } from '../../stores/appStore'
import { utilsApi, type AppInfo } from '@/api'
import type { Language, LineNumbersMode, LogLevel, ThemeMode } from '@/types/settings'
import styles from './SettingsContent.module.css'

/**
 * 设置页（对等 Vue 版 SettingsContent.vue：四分区，12 个设置项全部即时保存）。
 * Vue 的可写 computed → 受控 value + store setter（持久化在 setter 内同步执行——Slice 4 模式）。
 */

interface SettingsContentProps {
  embedded?: boolean
}

interface FontOption { label: string; value: string }

export default function SettingsContent({ embedded = false }: SettingsContentProps) {
  const { t, i18n } = useTranslation()
  const theme = useAppTheme()

  const themeMode = useAppStore((s) => s.themeMode)
  const language = useAppStore((s) => s.language)
  const logLevel = useAppStore((s) => s.logLevel)
  const interfaceSettings = useAppStore((s) => s.interfaceSettings)
  const editorSettings = useAppStore((s) => s.editorSettings)
  const databaseSettings = useAppStore((s) => s.databaseSettings)

  const [currentSection, setCurrentSection] = useState<'interface' | 'editor' | 'database' | 'about'>('interface')
  const [appInfo, setAppInfo] = useState<AppInfo | null>(null)

  function withDefaultLabel(label: string): string {
    return `${label} (${t('common.default_prefix')})`
  }
  function withCurrentLabel(label: string): string {
    return `${label} (${t('settings_page.current_label')})`
  }
  function withNonMonospaceLabel(label: string): string {
    return `${label} (${t('settings_page.non_monospace_label')})`
  }

  function extractFirstFont(value: string): string {
    const first = value.split(',')[0].trim().replace(/^["']|["']$/g, '')
    return first || value
  }

  const FALLBACK_INTERFACE_FONTS: FontOption[] = [
    { label: withDefaultLabel('Inter / SF Pro Display'), value: `Inter, "SF Pro Display", "Segoe UI", sans-serif` },
    { label: 'System UI', value: `system-ui, -apple-system, "Segoe UI", Roboto, sans-serif` },
  ]

  const FALLBACK_EDITOR_FONTS: FontOption[] = [
    { label: withDefaultLabel('JetBrains Mono'), value: `"JetBrains Mono"` },
    { label: 'Fira Code', value: `"Fira Code"` },
    { label: 'Cascadia Code', value: `"Cascadia Code"` },
    { label: 'Consolas', value: `"Consolas"` },
    { label: 'Courier New', value: `"Courier New"` },
  ]

  const [interfaceFontOptions, setInterfaceFontOptions] = useState<FontOption[]>(FALLBACK_INTERFACE_FONTS)
  const [editorFontOptions, setEditorFontOptions] = useState<FontOption[]>(FALLBACK_EDITOR_FONTS)

  function hasOptionWithValue(options: FontOption[], value: string): boolean {
    const norm = value.toLowerCase().replace(/^["']|["']$/g, '').trim()
    return options.some((o) => {
      const optNorm = o.value.toLowerCase().replace(/^["']|["']$/g, '').trim()
      return optNorm === norm
    })
  }

  const interfaceFontOptionsEffective = (() => {
    const options = [...interfaceFontOptions]
    const current = interfaceSettings.fontFamily
    if (current && !hasOptionWithValue(options, current)) {
      options.unshift({ label: withCurrentLabel(extractFirstFont(current)), value: current })
    }
    return options
  })()

  const editorFontOptionsEffective = (() => {
    const options = [...editorFontOptions]
    const current = editorSettings.fontFamily
    if (current && !hasOptionWithValue(options, current)) {
      options.unshift({ label: withCurrentLabel(extractFirstFont(current)), value: current })
    }
    return options
  })()

  const filterFontOption = (input: string, option?: FontOption) => {
    if (!option) return false
    return option.label.toLowerCase().includes(input.toLowerCase())
      || option.value.toLowerCase().includes(input.toLowerCase())
  }

  // 字体列表与应用信息加载（照抄策略：失败保留兜底选项）
  useEffect(() => {
    void (async () => {
      try {
        const fonts = await utilsApi.getSystemFonts()
        if (!fonts || fonts.length === 0) return

        const allFonts = fonts.map((f) => ({ label: f.family, value: `"${f.family}", sans-serif` }))
        const monoFonts = fonts.filter((f) => f.is_monospace).map((f) => ({ label: f.family, value: `"${f.family}"` }))
        const otherFonts = fonts.filter((f) => !f.is_monospace).map((f) => ({ label: withNonMonospaceLabel(f.family), value: `"${f.family}"` }))

        setInterfaceFontOptions([...FALLBACK_INTERFACE_FONTS, ...allFonts])
        setEditorFontOptions([...FALLBACK_EDITOR_FONTS, ...monoFonts, ...otherFonts.slice(0, 150)])
      } catch {
        console.warn('无法加载系统字体列表，使用内置选项')
      }
    })()
    void (async () => {
      try {
        setAppInfo(await utilsApi.getAppInfo())
      } catch (error) {
        console.warn('无法加载应用信息', error)
      }
    })()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const logLevelOptions = [
    { label: 'Error', value: 'error' },
    { label: 'Warn', value: 'warn' },
    { label: 'Info', value: 'info' },
    { label: 'Debug', value: 'debug' },
    { label: 'Trace', value: 'trace' },
  ]

  const currentSectionTitle = currentSection === 'interface'
    ? t('settings_page.interface_preferences')
    : currentSection === 'editor'
      ? t('settings_page.editor_preferences')
      : currentSection === 'database'
        ? t('settings_page.database_preferences')
        : t('settings_page.about_preferences')

  const currentSectionDescription = currentSection === 'interface'
    ? t('settings_page.interface_description')
    : currentSection === 'editor'
      ? t('settings_page.editor_description')
      : currentSection === 'database'
        ? t('settings_page.database_description')
        : t('settings_page.about_description')

  const appDisplayName = (() => {
    const raw = appInfo?.app_name?.trim()
    if (!raw) return 'Kudu'
    if (raw.toLowerCase() === 'kudu') return 'Kudu'
    return raw.charAt(0).toUpperCase() + raw.slice(1)
  })()

  function formatDisplayDate(value?: string | null): string {
    if (!value) return '-'
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return value
    return new Intl.DateTimeFormat(i18n.language, {
      year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
    }).format(date)
  }

  function formatBuildTimestamp(value?: string | null): string {
    if (!value) return '-'
    const seconds = Number(value)
    if (!Number.isFinite(seconds) || seconds <= 0) return value
    return formatDisplayDate(new Date(seconds * 1000).toISOString())
  }

  async function openExternalLink(url?: string | null) {
    if (!url) return
    try {
      await utilsApi.openExternalUrl(url)
    } catch (error) {
      console.warn('无法打开外部链接', error)
    }
  }

  const store = useAppStore.getState

  const renderSettingRow = (label: string, help: string, control: React.ReactNode) => (
    <div className={styles.settingRow}>
      <div className={styles.settingMeta}>
        <div className={styles.settingLabel}>{label}</div>
        <div className={`help-text ${styles.settingHelp}`}>{help}</div>
      </div>
      {control}
    </div>
  )

  const navItems: Array<{ key: typeof currentSection; label: string }> = [
    { key: 'interface', label: t('settings_page.interface_title') },
    { key: 'editor', label: t('settings_page.editor_title') },
    { key: 'database', label: t('settings_page.database_title') },
    { key: 'about', label: t('settings_page.about_title') },
  ]

  return (
    <div className={`${styles.settingsEditor} ${embedded ? styles.embedded : ''}`}>
      <aside className={styles.settingsNav}>
        <div className={`app-section-title ${styles.settingsNavTitle}`}>{t('common.settings')}</div>
        {navItems.map((item) => (
          <button
            key={item.key}
            type="button"
            className={`interactive-row ${styles.settingsNavItem} ${currentSection === item.key ? styles.active : ''}`}
            onClick={() => setCurrentSection(item.key)}
          >
            {item.label}
          </button>
        ))}
      </aside>

      <main className={styles.settingsMain}>
        {currentSection !== 'about' && (
          <div className={`section-header ${styles.settingsHeader}`}>
            <div className={styles.settingsHeading}>
              <h1>{currentSectionTitle}</h1>
              <p>{currentSectionDescription}</p>
              <div className={`app-subtle-note ${styles.settingsSubtle}`}>{t('settings_page.instant_save_hint')}</div>
            </div>
          </div>
        )}

        {currentSection === 'interface' && (
          <section className={styles.settingsGroup}>
            <div className={`setting-group-title ${styles.settingsGroupTitle}`}>{t('settings_page.appearance_group')}</div>
            {renderSettingRow(t('common.theme'), t('settings_page.theme_help'), (
              <Select
                value={themeMode}
                onChange={(v) => store().setThemeMode(v as ThemeMode)}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={[
                  { value: 'light', label: t('settings_page.theme_light') },
                  { value: 'dark', label: t('settings_page.theme_dark') },
                  { value: 'system', label: t('settings_page.theme_system') },
                ]}
              />
            ))}
            {renderSettingRow(t('settings_page.current_theme'), t('settings_page.current_theme_help'), (
              <Input
                value={theme === 'dark' ? t('settings_page.theme_dark') : t('settings_page.theme_light')}
                className={`${styles.settingSelect} ${styles.compact}`}
                readOnly
              />
            ))}
            {renderSettingRow(t('settings_page.interface_font'), t('settings_page.interface_font_help'), (
              <Select
                value={interfaceSettings.fontFamily}
                onChange={(v) => store().setInterfaceFontFamily(String(v))}
                className={styles.settingSelect}
                showSearch
                filterOption={filterFontOption}
                options={interfaceFontOptionsEffective}
                placeholder={t('settings_page.interface_font_placeholder')}
              />
            ))}
            {renderSettingRow(t('common.language'), t('settings_page.language_help'), (
              <Select
                value={language}
                onChange={(v) => store().setLanguage(v as Language)}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={[
                  { value: 'zh-CN', label: t('settings_page.language_zh_cn') },
                  { value: 'en-US', label: t('settings_page.language_en_us') },
                ]}
              />
            ))}
            {renderSettingRow(t('settings_page.log_level'), t('settings_page.log_level_help'), (
              <Select
                value={logLevel}
                onChange={(v) => store().setLogLevel(v as LogLevel)}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={logLevelOptions}
              />
            ))}
          </section>
        )}

        {currentSection === 'editor' && (
          <section className={styles.settingsGroup}>
            <div className={`setting-group-title ${styles.settingsGroupTitle}`}>{t('settings_page.editor_typography_group')}</div>
            {renderSettingRow(t('settings_page.editor_font'), t('settings_page.editor_font_help'), (
              <Select
                value={editorSettings.fontFamily}
                onChange={(v) => store().setEditorFontFamily(String(v))}
                className={styles.settingSelect}
                showSearch
                filterOption={filterFontOption}
                options={editorFontOptionsEffective}
                placeholder={t('settings_page.editor_font_placeholder')}
              />
            ))}
            {renderSettingRow(t('settings_page.font_size'), t('settings_page.font_size_help'), (
              <InputNumber
                value={editorSettings.fontSize}
                onChange={(v) => store().setEditorFontSize(Number(v || 14))}
                min={12}
                max={24}
                className={`${styles.settingSelect} ${styles.compact}`}
              />
            ))}
            {renderSettingRow(t('settings_page.line_numbers'), t('settings_page.line_numbers_help'), (
              <Select
                value={editorSettings.lineNumbers}
                onChange={(v) => store().setEditorLineNumbers(v as LineNumbersMode)}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={[
                  { value: 'on', label: t('settings_page.option_on') },
                  { value: 'off', label: t('settings_page.option_off') },
                ]}
              />
            ))}
            {renderSettingRow(t('settings_page.minimap'), t('settings_page.minimap_help'), (
              <Select
                value={editorSettings.minimap ? 'on' : 'off'}
                onChange={(v) => store().setEditorMinimap(v === 'on')}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={[
                  { value: 'on', label: t('settings_page.option_on') },
                  { value: 'off', label: t('settings_page.option_off') },
                ]}
              />
            ))}
          </section>
        )}

        {currentSection === 'database' && (
          <section className={styles.settingsGroup}>
            <div className={`setting-group-title ${styles.settingsGroupTitle}`}>{t('settings_page.database_connection_group')}</div>
            <Alert type="info" showIcon className={styles.settingsNote} message={t('settings_page.database_defaults_scope')} />
            {renderSettingRow(t('settings_page.mysql_charset'), t('settings_page.mysql_charset_help'), (
              <Select
                value={databaseSettings.mysqlCharset}
                onChange={(v) => store().setMysqlCharset(String(v))}
                className={`${styles.settingSelect} ${styles.compact}`}
                options={['utf8mb4', 'utf8', 'latin1', 'gbk'].map((v) => ({ value: v, label: v }))}
              />
            ))}
            {renderSettingRow(t('settings_page.mysql_init_sql'), t('settings_page.mysql_init_sql_help'), (
              <Input.TextArea
                value={databaseSettings.mysqlInitSql}
                onChange={(e) => store().setMysqlInitSql(e.target.value)}
                rows={4}
                className={styles.settingTextarea}
                placeholder={t('settings_page.mysql_init_sql_placeholder')}
              />
            ))}
          </section>
        )}

        {currentSection === 'about' && (
          <>
            <section className={styles.aboutHeroCard}>
              <h2 className={styles.aboutHeroTitle}>{appDisplayName}</h2>
              <p className={styles.aboutHeroDescription}>{t('settings_page.about_summary')}</p>
              <div className={styles.aboutHeroMeta}>
                <span className={styles.aboutHeroBadge}>v{appInfo?.version || '-'}</span>
                {appInfo?.git_short_commit && <span className={styles.aboutHeroBadge}>{appInfo.git_short_commit}</span>}
              </div>
              <button type="button" className={styles.aboutPrimaryLink} onClick={() => void openExternalLink(appInfo?.repository_url)}>
                {t('settings_page.about_open_github')}
              </button>
            </section>

            <section className={styles.aboutInfoCard}>
              <div className={`${styles.settingRow} ${styles.settingRowDisplay}`}>
                <div className={styles.settingMeta}>
                  <div className={styles.settingLabel}>{t('settings_page.about_version')}</div>
                </div>
                <div className={styles.settingDisplayValue}>{appInfo?.version || '-'}</div>
              </div>
              <div className={`${styles.settingRow} ${styles.settingRowDisplay}`}>
                <div className={styles.settingMeta}>
                  <div className={styles.settingLabel}>{t('settings_page.about_git_commit')}</div>
                </div>
                <div className={styles.settingDisplayValue}>{appInfo?.git_short_commit || appInfo?.git_commit || '-'}</div>
              </div>
              <div className={`${styles.settingRow} ${styles.settingRowDisplay}`}>
                <div className={styles.settingMeta}>
                  <div className={styles.settingLabel}>{t('settings_page.about_build_time')}</div>
                </div>
                <div className={styles.settingDisplayValue}>{formatBuildTimestamp(appInfo?.build_time)}</div>
              </div>
            </section>
          </>
        )}
      </main>
    </div>
  )
}

// src/components/settings/SettingsContent.vue
<template>
  <div class="settings-editor" :class="{ embedded }">
    <aside class="settings-nav">
      <div class="app-section-title settings-nav-title">{{ $t('common.settings') }}</div>
      <button type="button" class="interactive-row settings-nav-item" :class="{ active: currentSection === 'interface' }" @click="selectedKeys = ['interface']">
        {{ $t('settings_page.interface_title') }}
      </button>
      <button type="button" class="interactive-row settings-nav-item" :class="{ active: currentSection === 'editor' }" @click="selectedKeys = ['editor']">
        {{ $t('settings_page.editor_title') }}
      </button>
      <button type="button" class="interactive-row settings-nav-item" :class="{ active: currentSection === 'database' }" @click="selectedKeys = ['database']">
        {{ $t('settings_page.database_title') }}
      </button>
      <button type="button" class="interactive-row settings-nav-item" :class="{ active: currentSection === 'about' }" @click="selectedKeys = ['about']">
        {{ $t('settings_page.about_title') }}
      </button>
    </aside>

    <main class="settings-main">
      <div v-if="currentSection !== 'about'" class="section-header settings-header">
        <div class="settings-heading">
          <h1>{{ currentSectionTitle }}</h1>
          <p>{{ currentSectionDescription }}</p>
          <div v-if="currentSection !== 'about'" class="app-subtle-note settings-subtle">{{ $t('settings_page.instant_save_hint') }}</div>
        </div>
      </div>

      <template v-if="currentSection === 'interface'">
        <section class="settings-group">
          <div class="setting-group-title settings-group-title">{{ $t('settings_page.appearance_group') }}</div>
          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('common.theme') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.theme_help') }}</div>
            </div>
            <a-select v-model:value="themeModeModel" class="setting-select compact">
              <a-select-option value="light">{{ $t('settings_page.theme_light') }}</a-select-option>
              <a-select-option value="dark">{{ $t('settings_page.theme_dark') }}</a-select-option>
              <a-select-option value="system">{{ $t('settings_page.theme_system') }}</a-select-option>
            </a-select>
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.current_theme') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.current_theme_help') }}</div>
            </div>
            <a-input :value="appStore.theme === 'dark' ? $t('settings_page.theme_dark') : $t('settings_page.theme_light')" class="setting-select compact" readonly />
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.interface_font') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.interface_font_help') }}</div>
            </div>
            <a-select
              v-model:value="interfaceFontModel"
              class="setting-select"
              show-search
              :filter-option="filterFontOption"
              :options="interfaceFontOptionsEffective"
              :placeholder="$t('settings_page.interface_font_placeholder')"
            />
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('common.language') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.language_help') }}</div>
            </div>
            <a-select v-model:value="languageModel" class="setting-select compact">
              <a-select-option value="zh-CN">{{ $t('settings_page.language_zh_cn') }}</a-select-option>
              <a-select-option value="en-US">{{ $t('settings_page.language_en_us') }}</a-select-option>
            </a-select>
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.log_level') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.log_level_help') }}</div>
            </div>
            <a-select v-model:value="logLevelModel" class="setting-select compact" :options="logLevelOptions" />
          </div>
        </section>
      </template>

      <template v-else-if="currentSection === 'editor'">
        <section class="settings-group">
          <div class="setting-group-title settings-group-title">{{ $t('settings_page.editor_typography_group') }}</div>
          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.editor_font') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.editor_font_help') }}</div>
            </div>
            <a-select
              v-model:value="editorFontModel"
              class="setting-select"
              show-search
              :filter-option="filterFontOption"
              :options="editorFontOptionsEffective"
              :placeholder="$t('settings_page.editor_font_placeholder')"
            />
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.font_size') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.font_size_help') }}</div>
            </div>
            <a-input-number v-model:value="fontSizeModel" :min="12" :max="24" class="setting-select compact" />
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.line_numbers') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.line_numbers_help') }}</div>
            </div>
            <a-select v-model:value="lineNumbersModel" class="setting-select compact">
              <a-select-option value="on">{{ $t('settings_page.option_on') }}</a-select-option>
              <a-select-option value="off">{{ $t('settings_page.option_off') }}</a-select-option>
            </a-select>
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.minimap') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.minimap_help') }}</div>
            </div>
            <a-select v-model:value="minimapModeModel" class="setting-select compact">
              <a-select-option value="on">{{ $t('settings_page.option_on') }}</a-select-option>
              <a-select-option value="off">{{ $t('settings_page.option_off') }}</a-select-option>
            </a-select>
          </div>
        </section>
      </template>

      <template v-else-if="currentSection === 'database'">
        <section class="settings-group">
          <div class="setting-group-title settings-group-title">{{ $t('settings_page.database_connection_group') }}</div>
          <a-alert
            type="info"
            show-icon
            class="settings-note"
            :message="$t('settings_page.database_defaults_scope')"
          />

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.mysql_charset') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.mysql_charset_help') }}</div>
            </div>
            <a-select v-model:value="mysqlCharsetModel" class="setting-select compact">
              <a-select-option value="utf8mb4">utf8mb4</a-select-option>
              <a-select-option value="utf8">utf8</a-select-option>
              <a-select-option value="latin1">latin1</a-select-option>
              <a-select-option value="gbk">gbk</a-select-option>
            </a-select>
          </div>

          <div class="setting-row">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.mysql_init_sql') }}</div>
              <div class="help-text setting-help">{{ $t('settings_page.mysql_init_sql_help') }}</div>
            </div>
            <a-textarea
              v-model:value="mysqlInitSqlModel"
              :rows="4"
              class="setting-textarea"
              :placeholder="$t('settings_page.mysql_init_sql_placeholder')"
            />
          </div>
        </section>
      </template>

      <template v-else>
        <section class="about-hero-card">
          <h2 class="about-hero-title">{{ appDisplayName }}</h2>
          <p class="about-hero-description">{{ $t('settings_page.about_summary') }}</p>
          <div class="about-hero-meta">
            <span class="about-hero-badge">v{{ appInfo?.version || '-' }}</span>
            <span v-if="appInfo?.git_short_commit" class="about-hero-badge">{{ appInfo.git_short_commit }}</span>
          </div>
          <button type="button" class="about-primary-link" @click="openExternalLink(appInfo?.repository_url)">
            {{ $t('settings_page.about_open_github') }}
          </button>
        </section>

        <section class="about-info-card">
          <div class="setting-row setting-row-display">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.about_version') }}</div>
            </div>
            <div class="setting-display-value">{{ appInfo?.version || '-' }}</div>
          </div>

          <div class="setting-row setting-row-display">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.about_git_commit') }}</div>
            </div>
            <div class="setting-display-value">{{ appInfo?.git_short_commit || appInfo?.git_commit || '-' }}</div>
          </div>

          <div class="setting-row setting-row-display">
            <div class="setting-meta">
              <div class="setting-label">{{ $t('settings_page.about_build_time') }}</div>
            </div>
            <div class="setting-display-value">{{ formatBuildTimestamp(appInfo?.build_time) }}</div>
          </div>
        </section>
      </template>
    </main>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppStore, type Language, type LogLevel, type ThemeMode } from '@/stores/app'
import { utilsApi, type AppInfo } from '@/api'

withDefaults(defineProps<{
  embedded?: boolean
}>(), {
  embedded: false,
})

defineEmits<{
  close: []
}>()

const appStore = useAppStore()
const { t, locale } = useI18n()
const selectedKeys = ref<string[]>(['interface'])
const appInfo = ref<AppInfo | null>(null)

const filterFontOption = (input: string, option: { label: string; value: string }) => {
  return option.label.toLowerCase().includes(input.toLowerCase()) || option.value.toLowerCase().includes(input.toLowerCase())
}

function withDefaultLabel(label: string): string {
  return `${label} (${t('common.default_prefix')})`
}

function withCurrentLabel(label: string): string {
  return `${label} (${t('settings_page.current_label')})`
}

function withNonMonospaceLabel(label: string): string {
  return `${label} (${t('settings_page.non_monospace_label')})`
}

// 从 CSS font-family 值中提取首个字体名（用于自定义选项的 label）
function extractFirstFont(value: string): string {
  // 去掉引号，取出第一个逗号前的字体名
  const first = value.split(',')[0].trim().replace(/^["']|["']$/g, '')
  return first || value
}

// 兜底字体选项（系统字体列表加载失败时使用）
const FALLBACK_INTERFACE_FONTS = [
  { label: withDefaultLabel('Inter / SF Pro Display'), value: `Inter, "SF Pro Display", "Segoe UI", sans-serif` },
  { label: 'System UI', value: `system-ui, -apple-system, "Segoe UI", Roboto, sans-serif` },
]

const FALLBACK_EDITOR_FONTS = [
  { label: withDefaultLabel('JetBrains Mono'), value: `"JetBrains Mono"` },
  { label: 'Fira Code', value: `"Fira Code"` },
  { label: 'Cascadia Code', value: `"Cascadia Code"` },
  { label: 'Consolas', value: `"Consolas"` },
  { label: 'Courier New', value: `"Courier New"` },
]

const interfaceFontOptions = ref<{ label: string; value: string }[]>([...FALLBACK_INTERFACE_FONTS])
const editorFontOptions = ref<{ label: string; value: string }[]>([...FALLBACK_EDITOR_FONTS])

// 确保当前选中的值始终出现在下拉列表中（大小写不敏感去重）
function hasOptionWithValue(options: { label: string; value: string }[], value: string): boolean {
  const norm = value.toLowerCase().replace(/^["']|["']$/g, '').trim()
  return options.some(o => {
    const optNorm = o.value.toLowerCase().replace(/^["']|["']$/g, '').trim()
    return optNorm === norm
  })
}

const interfaceFontOptionsEffective = computed(() => {
  const options = [...interfaceFontOptions.value]
  const current = appStore.interfaceSettings.fontFamily
  if (current && !hasOptionWithValue(options, current)) {
    options.unshift({ label: withCurrentLabel(extractFirstFont(current)), value: current })
  }
  return options
})

const editorFontOptionsEffective = computed(() => {
  const options = [...editorFontOptions.value]
  const current = appStore.editorSettings.fontFamily
  if (current && !hasOptionWithValue(options, current)) {
    options.unshift({ label: withCurrentLabel(extractFirstFont(current)), value: current })
  }
  return options
})

async function loadSystemFonts() {
  try {
    const fonts = await utilsApi.getSystemFonts()
    if (!fonts || fonts.length === 0) return

    // 构建所有系统字体的选项（供界面字体使用）
    const allFonts = fonts.map(f => ({
      label: f.family,
      value: `"${f.family}", sans-serif`,
    }))

    // 等宽字体优先（供编辑器字体使用）
    const monoFonts = fonts
      .filter(f => f.is_monospace)
      .map(f => ({
        label: f.family,
        value: `"${f.family}"`,
      }))
    const otherFonts = fonts
      .filter(f => !f.is_monospace)
      .map(f => ({
        label: withNonMonospaceLabel(f.family),
        value: `"${f.family}"`,
      }))

    // 界面字体：常用兜底字体 + 所有系统字体
    interfaceFontOptions.value = [
      ...FALLBACK_INTERFACE_FONTS,
      ...allFonts,
    ]

    // 编辑器字体：常用兜底字体 + 等宽系统字体优先 + 其他字体
    editorFontOptions.value = [
      ...FALLBACK_EDITOR_FONTS,
      ...monoFonts,
      ...otherFonts.slice(0, 150),
    ]
  } catch {
    // 系统字体加载失败，保留兜底选项
    console.warn('无法加载系统字体列表，使用内置选项')
  }
}

async function loadAppInfo() {
  try {
    appInfo.value = await utilsApi.getAppInfo()
  } catch (error) {
    console.warn('无法加载应用信息', error)
  }
}

function formatDisplayDate(value?: string | null): string {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value
  return new Intl.DateTimeFormat(locale.value, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  }).format(date)
}

function formatBuildTimestamp(value?: string | null): string {
  if (!value) return '-'
  const seconds = Number(value)
  if (!Number.isFinite(seconds) || seconds <= 0) return value
  return formatDisplayDate(new Date(seconds * 1000).toISOString())
}

async function openExternalLink(url?: string | null) {
  if (!url) return
  try {
    await utilsApi.openExternalUrl(url)
  } catch (error) {
    console.warn('无法打开外部链接', error)
  }
}

onMounted(() => {
  loadSystemFonts()
  loadAppInfo()
})

const logLevelOptions = [
  { label: 'Error', value: 'error' },
  { label: 'Warn', value: 'warn' },
  { label: 'Info', value: 'info' },
  { label: 'Debug', value: 'debug' },
  { label: 'Trace', value: 'trace' },
]

const currentSection = computed(() => selectedKeys.value[0] || 'interface')
const currentSectionTitle = computed(() => {
  if (currentSection.value === 'interface') return t('settings_page.interface_preferences')
  if (currentSection.value === 'editor') return t('settings_page.editor_preferences')
  if (currentSection.value === 'database') return t('settings_page.database_preferences')
  return t('settings_page.about_preferences')
})
const currentSectionDescription = computed(() => {
  if (currentSection.value === 'interface') return t('settings_page.interface_description')
  if (currentSection.value === 'editor') return t('settings_page.editor_description')
  if (currentSection.value === 'database') return t('settings_page.database_description')
  return t('settings_page.about_description')
})
const appDisplayName = computed(() => {
  const raw = appInfo.value?.app_name?.trim()
  if (!raw) return 'Kudu'
  if (raw.toLowerCase() === 'kudu') return 'Kudu'
  return raw.charAt(0).toUpperCase() + raw.slice(1)
})

const themeModeModel = computed({
  get: () => appStore.themeMode,
  set: (value: ThemeMode) => appStore.setThemeMode(value),
})
const languageModel = computed({
  get: () => appStore.language,
  set: (value: Language) => appStore.setLanguage(value),
})
const logLevelModel = computed({
  get: () => appStore.logLevel,
  set: (value: LogLevel) => appStore.setLogLevel(value),
})
const fontSizeModel = computed({
  get: () => appStore.editorSettings.fontSize,
  set: (value: number | null) => appStore.setEditorFontSize(Number(value || 14)),
})
const interfaceFontModel = computed({
  get: () => appStore.interfaceSettings.fontFamily,
  set: (value: string) => appStore.setInterfaceFontFamily(value),
})
const editorFontModel = computed({
  get: () => appStore.editorSettings.fontFamily,
  set: (value: string) => appStore.setEditorFontFamily(value),
})
const minimapModeModel = computed({
  get: () => appStore.editorSettings.minimap ? 'on' : 'off',
  set: (value: string) => appStore.setEditorMinimap(value === 'on'),
})
const lineNumbersModel = computed({
  get: () => appStore.editorSettings.lineNumbers,
  set: (value: 'on' | 'off') => appStore.setEditorLineNumbers(value),
})
const mysqlCharsetModel = computed({
  get: () => appStore.databaseSettings.mysqlCharset,
  set: (value: string) => appStore.setMysqlCharset(value),
})
const mysqlInitSqlModel = computed({
  get: () => appStore.databaseSettings.mysqlInitSql,
  set: (value: string) => appStore.setMysqlInitSql(value),
})
</script>

<style scoped>
.settings-editor {
  display: flex;
  height: 100%;
  min-height: 0;
  background: var(--surface);
  color: var(--app-text);
}

.settings-editor.embedded {
  border-top: 1px solid var(--border-color);
}

.settings-nav {
  width: 188px;
  flex-shrink: 0;
  padding: 8px 8px;
  border-right: 1px solid var(--border-color);
  background: transparent;
}

.settings-nav-item {
  width: 100%;
  padding: 6px 8px;
  border: 0;
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--app-text-muted);
  font-size: 13px;
  text-align: left;
}

.settings-nav-item + .settings-nav-item {
  margin-top: 2px;
}

.settings-nav-item.active {
  background: var(--color-primary-active-bg);
  color: var(--color-primary);
}

.settings-main {
  flex: 1;
  min-width: 0;
  overflow: auto;
  padding: 10px 16px 16px;
  background: transparent;
}

.settings-header {
  margin-bottom: 10px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--border-color-muted);
}

.settings-heading p {
  margin: 4px 0 0;
  color: var(--app-text-subtle);
  font-size: 12px;
  line-height: 1.5;
}

.settings-group {
  margin-bottom: 10px;
  border: 0;
  border-radius: 0;
  overflow: visible;
  background: transparent;
}

.dark-mode .settings-group {
  background: transparent;
}

.setting-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
  padding: 10px 0;
  border-bottom: 1px solid var(--border-color-muted);
}

.setting-row:last-child {
  border-bottom: none;
}

.setting-meta {
  flex: 1;
  min-width: 0;
}

.setting-row-display {
  align-items: flex-start;
}

.setting-display-value {
  max-width: 420px;
  min-width: 180px;
  padding-top: 1px;
  color: var(--app-text);
  font-size: 13px;
  line-height: 1.6;
  text-align: right;
  word-break: break-word;
}

.setting-label {
  margin-bottom: 2px;
  font-size: 13px;
  font-weight: 500;
}

.setting-select {
  width: 240px;
}

.setting-select.compact {
  width: 180px;
}

.setting-textarea {
  width: 320px;
}

.settings-note {
  margin: 16px;
  margin-bottom: 0;
}

.about-hero-card {
  margin-bottom: 16px;
  padding: 20px 22px;
  border: 1px solid var(--border-color);
  border-radius: 14px;
  background: linear-gradient(180deg, var(--surface) 0%, var(--color-fill-2, rgba(127,127,127,0.06)) 100%);
}

.about-hero-title {
  margin: 0;
  color: var(--app-text);
  font-size: 28px;
  line-height: 1.2;
}

.about-hero-description {
  max-width: 680px;
  margin: 10px 0 0;
  color: var(--app-text-subtle);
  font-size: 14px;
  line-height: 1.7;
}

.about-hero-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 14px;
}

.about-hero-badge {
  display: inline-flex;
  align-items: center;
  padding: 3px 10px;
  border: 1px solid var(--border-color);
  border-radius: 999px;
  background: var(--surface);
  color: var(--app-text-subtle);
  font-size: 12px;
}

.about-primary-link {
  margin-top: 16px;
  padding: 8px 14px;
  border: 0;
  border-radius: 10px;
  background: var(--color-primary);
  color: white;
  font-size: 13px;
  cursor: pointer;
}

.about-primary-link:hover {
  opacity: 0.92;
}

.about-info-card {
  border: 1px solid var(--border-color);
  border-radius: 14px;
  padding: 0 18px;
  background: var(--surface);
}

.settings-link-button {
  max-width: 420px;
  min-width: 180px;
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--color-primary);
  font-size: 13px;
  line-height: 1.6;
  text-align: right;
  word-break: break-all;
  cursor: pointer;
}

.settings-link-button:hover {
  text-decoration: underline;
}

@media (max-width: 900px) {
  .settings-editor {
    flex-direction: column;
  }

  .settings-nav {
    width: 100%;
    border-right: 0;
    border-bottom: 1px solid var(--border-color);
  }

  .settings-header,
  .setting-row {
    flex-direction: column;
    align-items: stretch;
  }

  .about-info-card {
    padding: 0 14px;
  }

  .setting-display-value,
  .settings-link-button,
  .setting-select,
  .setting-select.compact,
  .setting-textarea {
    width: 100%;
  }
}
</style>
